config/routes.rb
Rails.application.routes.draw do
  get "publications/locations"
  resources :publications
  get "pages/map"
  devise_for :users , controllers: {
    registrations: 'users/registrations', :omniauth_callbacks =>
  "users/omniauth_callbacks"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
end

app/models/publication.rb
class Publication < ApplicationRecord
  validates :name, :description, :photo, :latitude, :longitude, presence: true
    belongs_to :user
    mount_uploader :photo, ImageUploader
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_pet, only: [:destroy]

  def index
    @publications = Publication.all
  end
  def new
    @publication = Publication.new
  end

  def create
    @publication = Publication.new(pet_params)
    @publication.user = current_user
    respond_to do |format|
      if @publication.save
        format.html { redirect_to publications_path @publication, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @publication = Publication.find(params[:id])
  end

  def edit
  end

  def update
  end

  def locations
    render json: Publication.select(:id, :name, :latitude, :longitude, :photo).to_json
  end

  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Eliminaste la mascota' }
      format.json { head :no_content }
    end
  end

  private
  def pet_params
    params.require(:publication).permit(:name, :latitude, :longitude, :type, :photo, :adopted, :injured, :description)
  end

  def set_pet
    @publication = Publication.find(params[:id])
  end
end

app/views/publications/edit.html.erb
<h1>Pets#edit</h1>
<p>Find me in app/views/pets/edit.html.erb</p>

app/views/publications/index.html.erb
<div class="new-pet">
	<div class="container pt-2 pb-2">
		<% if user_signed_in? %>
			<%= link_to 'Ingresa una nueva mascota', new_publication_path, class: "new-pet"%>
			<% else %>
			<h1 class="new-pet pt-1"><%= link_to 'Inicia sesión', new_user_session_path, class: :blanco %> o <%= link_to 'Regístrate', new_user_registration_path, class: :blanco %> para ingresar una nueva mascota</h1>
		<% end %>
	</div>
</div>

<div class="mascotas container">
	<div class="pt-5 container">
    <div class="container shadow-sm titulomascotashogar">
      <h1 class="p-2">Mascotas buscando hogar</h1>
    </div>

	</div>
	<div class="row container-fluid pb-5 pt-3">
			<% @publications.each do |pet| %>
				<div class="col-md-3 p-3">
					<div class="card shadow-sm bg-white">
						<a href="<%= publication_path(pet)%>">
							<p><%= image_tag pet.photo.url, class: :pet_photo %></p>
							<div class="card-body">
								<h2 class="card-title container"><%= pet.name %></h2>
							</div>
						</a>
					</div>
				</div>
			<% end %>
	</div>
</div>

app/views/publications/new.html.erb
<div class="p-5">
  <div class="row pt-5 nuevomapaback">
    <div class="col from-group pt-5">
      <div class="nueva container-fluid shadow-sm p-5">
        <%= form_with model: @publication, local: true do |f| %>
            <div class="shadow-sm container">
              <p><%= f.label :name, "Nombre" %></p>
              <p><%= f.text_field :name, class: "form-control" %></p>
            </div>
            <div class="field container shadow-sm">
              <p><%= f.label :photo, "Imagen" %></p>
              <p><%= f.file_field :photo, id: :photo_image %></p>
              </div>
            <div class="field container shadow-sm">
              <p><%= f.label :description, "Descripción" %></p>
              <p><%= f.text_area :description, class: "form-control-lg", rows: 6 %></p>
            </div>
            <div class="">
              <p><%= f.hidden_field :latitude %></p>
              <p><%= f.hidden_field :longitude %></p>
            </div>
            <div class="container">
              <%= f.submit "Enviar", class: "btn shadow-sm" %>
            </div>
        <% end %>
      </div>
    </div>
    <div class="col p-3 mapanuevo shadow-sm">
      <div class="col container" id="mapid">
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function(){
	    var mymap = null;
      mymap = L.map('mapid').locate({setView: true, maxZoom: 18});
	    createMap(mymap);
	    selectPetLocation(mymap);
	});
</script>

app/views/publications/show.html.erb
<div class="row p-5">
  <div class="col-4 container ">
    <div class="pet-show-new shadow-sm">
      <p><%= image_tag @publication.photo.url, class: 'showphoto' %></p>
      <div class="container">
        <h1><%= @publication.name %></h1>
        <p><%= @publication.description  %></p>
        <p><%= @publication.user.email %></p>
        <% if user_signed_in? %>
          <p class="container"><%= link_to 'Eliminar', publication_path(@publication), method: :delete, data: { confirm: 'Estás seguro que deseas eliminar esta mascota?' }, class: 'btn btn-sm' %></p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-8">
    <div class="">
  		<div class="container" id="mapid">
  		</div>
  	</div>
  </div>
</div>

<script>
	document.addEventListener('DOMContentLoaded', function(){
	    var mymap = null;
			mymap = L.map('mapid').setView([<%= @publication.latitude %>, <%= @publication.longitude %>], 16);
	    createMap(mymap);
      L.circle([<%= @publication.latitude %>, <%= @publication.longitude %>], {
        radius: 100
      }).addTo(mymap);
	});
</script>