config/routes.rb
Rails.application.routes.draw do
  get "publications/locations"
  resources :publications
  get "pages/map"
  devise_for :users , controllers: {
    registrations: 'users/registrations', :omniauth_callbacks =>
  "users/omniauth_callbacks"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon0.png', type: 'image/png' %>
    <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzI``xFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- FontAwesome -->
        <script src="https://kit.fontawesome.com/4f22120ef6.js" crossorigin="anonymous"></script>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- leaflet -->
      <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
       integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
       crossorigin=""/>
       <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
       integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
       crossorigin=""></script>
       <!-- font -->
       <link href="https://fonts.googleapis.com/css?family=Raleway:400,700&display=swap" rel="stylesheet">
       <link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet">
       <div id="fb-root"></div>
        <script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v5.0&appId=2202224806548067&autoLogAppEvents=1"></script>
  </head>

  <body>
    <div class="navcolor shadow-sm">
      <nav class="row navbar navbar-expand-lg navbar-dark">
          <div class="col-1">
            <a class="navbar-brand" href="<%= root_path %>"> <%= image_tag("top-odkasy-sketched-symbol.svg") %> DogMe </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
          <div class="col-3">
            <a class="navbar-brand" href="<%= root_path %>"> Inicio </a>
            <a class="navbar-brand" href="<%= pages_map_path %>"> Mapa </a>
            <a class="navbar-brand" href="<%= publications_path %>"> Mascotas </a>
          </div>

          <div class="col-5">
            <div class="">
              <% if user_signed_in? %>
          			<h2><%= link_to 'Ingresa una nueva mascota', new_publication_path, class:"blanco"%></h2>
          			<% else %>
          			<h2 class=""><%= link_to 'Ingresa una nueva mascota', new_user_session_path, class: :blanco %></h2>
          		<% end %>
            </div>
          </div>
          <div class="col-2">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown pl-4">
                  <% if user_signed_in? %>
                  <a href="#" class="dropdown-toggle navbar-brand" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Hola! <%= current_user.email.partition('@').first %> <span class="caret"></span></a>
                  <ul class="dropdown-menu pl-4">
                  <li><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: :blanco %></li>
                  <% else %>
                  <a href="#" class="dropdown-toggle navbar-brand" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ingreso <span class="caret"></span></a>
                  <ul class="dropdown-menu pl-4">
                  <li><%= link_to 'Inicia sesión', new_user_session_path, class: :blanco %></li>
                  <li><%= link_to 'Regístrate', new_user_registration_path, class: :blanco %></li>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
      </nav>

    </div>
    <div class="">
      <%= yield %>
    </div>
  </body>
  <div class="">

  </div>
  <footer class="footer-bs shadow-sm">
      <div class="row">
        <div class="col-md-5 footer-brand animated fadeInLeft pl-5 pr-5 pb-5">
            <a class="navbar-brand" href="<%= root_path %>"> <%= image_tag("top-odkasy-sketched-symbol.svg") %> </a>
              <p class="pt-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris</p>
        </div>
        <div class="col-md-4 footer-nav animated fadeInUp">
          <h4>Menu —</h4>
          <div class="col-md-6">
                <ul class="pages">
                    <li><a class="navbar-brand" href="<%= publications_path %>"> Mascotas </a></li>
                </ul>
            </div>
            <div class="col-md-6">
                <ul class="list">
                    <li><a href="#">Nosotros</a></li>
                    <li><a href="#">Contacto</a></li>
                </ul>
            </div>
          </div>
          <div class="col-md-3 footer-social animated fadeInDown">
            <h4>Síguenos</h4>
            <ul>
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Instagram</a></li>
              </ul>
          </div>
      </div>
  </footer>
</html>